export const TIP_TAP_LOCALE = {
    CONVERSION: '전환',
    MEDIA: '미디어',
    NO_RESULTS_FOUND: '결과 없음',
    NODE_LABEL: {
        PARAGRAPH: '텍스트',
        HEADING1: '제목1',
        HEADING2: '제목2',
        HEADING3: '제목3',
        LIST: '리스트',
        BULLET_LIST: '글머리 기호 목록',
        ORDERED_LIST: '번호 매기기 목록',
        CODE_BLOCK: '코드',
        BLOCKQUOTE: '인용문',
        CALLOUT: '콜아웃',
        HORIZONTAL_RULE: '구분선',
        HARD_BREAK: '줄 바꿈',
        TASK: '할 일',
        TASK_LIST: '할일 목록',
        SUMMARY: '토글',
        IMAGE: '이미지',
        YOUTUBE: '유튜브 영상',
        INPUT_YOUTUBE_URL: '유튜브 영상 URL을 입력하세요:',
        TABLE: '표',
    },
    MARK: {
        bold: '굵게',
        italic: '기울임',
        strike: '취소선',
        underline: '밑줄',
        code: '코드',
        subscript: '아래 첨자',
        superscript: '위 첨자',
    },
    COLOR: {
        TITLE: '텍스트 색',
        TEXT: '텍스트',
        BACKGROUND: '배경',
        COLOR: '색상',
        //
        DEFAULT: '기본',
        GRAY: '회색',
        BROWN: '갈색',
        ORANGE: '주황색',
        YELLOW: '노란색',
        GREEN: '초록색',
        BLUE: '파란색',
        PURPLE: '보라색',
        PINK: '분홍색',
        RED: '빨간색',
    },
    ALIGN: {
        TITLE: '정렬',
        LEFT: '왼쪽 정렬',
        CENTER: '가운데 정렬',
        RIGHT: '오른쪽 정렬',
        JUSTIFY: '양쪽 정렬',
    },
    LINK: {
        TITLE: '링크 추가',
    },
    DRAG_HANDLE: {
        MOVE: '옮기기',
        WITH_DRAG: '드래그해서',
    },
    TABLE_MENU: {
        ADD_COLUMN_BEFORE: '왼쪽에 열 추가',
        ADD_COLUMN_AFTER: '오른쪽에 열 추가',
        DELETE_COLUMN: '열 삭제',
        ADD_ROW_BEFORE: '위에 행 추가',
        ADD_ROW_AFTER: '아래에 행 추가',
        DELETE_ROW: '행 삭제',
        MERGE_CELLS: '셀 병합',
        SPLIT_CELL: '셀 분할',
        TOGGLE_HEADER_COLUMN: '제목 행 전환',
        TOGGLE_HEADER_ROW: '제목 열 전환',
    },
    IMAGE_UPLOAD_NODE: {
        CLICK_TO_UPLOAD: '클릭하여 이미지 업로드',
        OR_DRAG_DROP: '또는 끌어서 놓기',
        MAXIMUM_FILES: (limit: number) => `최대 ${limit}개 파일`,
        MAX_SIZE: (sizeMB: number) => `각 파일 크기 ${sizeMB}MB 이하`,
        UPLOADING: '업로드 중...',
        FAILED: '업로드 실패. 다시 시도해주세요.',
    },
};
