export const TIP_TAP_LOCALE = {
    CONVERSION: '전환',
    MEDIA: '미디어',
    NO_RESULTS_FOUND: '결과 없음',
    NODE_LABEL: {
        PARAGRAPH: '텍스트',
        HEADING1: '제목1',
        HEADING2: '제목2',
        HEADING3: '제목3',
        LIST: '리스트',
        BULLET_LIST: '글머리 기호 목록',
        ORDERED_LIST: '번호 매기기 목록',
        CODE_BLOCK: '코드',
        BLOCKQUOTE: '인용문',
        HORIZONTAL_RULE: '구분선',
        HARD_BREAK: '줄 바꿈',
        TASK: '할 일',
        TASK_LIST: '할일 목록',
        SUMMARY: '토글',
        IMAGE: '이미지',
        YOUTUBE: '유튜브 영상',
        INPUT_YOUTUBE_URL: '유튜브 영상 URL을 입력하세요:',
        TABLE: '표',
    },
    MARK: {
        bold: '굵게',
        italic: '기울임',
        strike: '취소선',
        underline: '밑줄',
        code: '코드',
        subscript: '아래 첨자',
        superscript: '위 첨자',
    },
    COLOR: {
        TITLE: '텍스트 색',
        TEXT: '텍스트',
        BACKGROUND: '배경',
        COLOR: '색상',
        //
        DEFAULT: '기본',
        GRAY: '회색',
        BROWN: '갈색',
        ORANGE: '주황색',
        YELLOW: '노란색',
        GREEN: '초록색',
        BLUE: '파란색',
        PURPLE: '보라색',
        PINK: '분홍색',
        RED: '빨간색',
    },
    ALIGN: {
        TITLE: '정렬',
        LEFT: '왼쪽 정렬',
        CENTER: '가운데 정렬',
        RIGHT: '오른쪽 정렬',
        JUSTIFY: '양쪽 정렬',
    },
    LINK: {
        TITLE: '링크 추가',
    },
    DRAG_HANDLE: {
        MOVE: '옮기기',
        WITH_DRAG: '드래그해서',
    },
};
